airbnb:
  outputs:
    dev:
      type: snowflake
      account: DVMZFSM-KC22031
      user: dbt

      role: TRANSFORM
      private_key_path: "secrets\\dbt_snowflake_pvt_key.p8"
      private_key_passphrase: "q"

      database: AIRBNB
      schema: DEV
      threads: 6
      warehouse: COMPUTE_WH
  target: dev
